# Generated by Django 5.2.6 on 2025-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Outlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
