# Generated by Django 5.2.6 on 2025-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlay",
            name="amount",
            field=models.BigIntegerField(),
        ),
    ]
