# Generated by Django 5.2.6 on 2025-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_income_user_outlay_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="outlay",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
