# Generated by Django 5.2.6 on 2025-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_income_date_alter_outlay_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="outlay",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
